# Generated by Django 5.1.1 on 2024-10-08 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sound_Flow_App', '0002_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_session', to='Sound_Flow_App.user'),
        ),
    ]
