# Generated by Django 5.1.1 on 2024-10-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sound_Flow_App', '0003_session_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='supported_engineers',
            field=models.ManyToManyField(related_name='supporters', to='Sound_Flow_App.user'),
        ),
    ]
