# Generated by Django 5.1.1 on 2024-10-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sound_Flow_App', '0005_session_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='role',
        ),
    ]
